export const environment = {
  production: true,
 endPointApi: "https://test-eazyvat2-app-api.azurewebsites.net",  
  //endPointApi: "localhost:5600",
  endPointApiSupplier: "https://test-eazyvat2-purchase-api.azurewebsites.net/",
  endPointSignalR: "https://test-eazyvat2-app-api.azurewebsites.net",  
  // endPointApi: "https://testeasyvatappapi.azurewebsites.net",  
  // endPointSignalR: "https://testeasyvatapi.azurewebsites.net",  
  scanApi: "https://api.anyline.com/v1/scan",
  // tslint:disable-next-line:max-line-length
  oldScanLicense:
    "eyAiZGVidWdSZXBvcnRpbmciOiAib24iLCAiaW9zSWRlbnRpZmllciI6IFsgImNvbS5hbnlsaW5lLndlYi50ZXN0IiBdLCAibGljZW5zZUtleVZlcnNpb24iOiAyLCAibWFqb3JWZXJzaW9uIjogIjExIiwgIm1heERheXNOb3RSZXBvcnRlZCI6IDAsICJwaW5nUmVwb3J0aW5nIjogdHJ1ZSwgInBsYXRmb3JtIjogWyAiaU9TIiwgIldlYiIgXSwgInNjb3BlIjogWyAiQUxMIiBdLCAic2hvd1BvcFVwQWZ0ZXJFeHBpcnkiOiBmYWxzZSwgInNob3dXYXRlcm1hcmsiOiBmYWxzZSwgInRvbGVyYW5jZURheXMiOiAwLCAidmFsaWQiOiAiMjAyMC0wMS0wMSIsICJ3ZWJJZGVudGlmaWVyIjogWyAiY29tLmFueWxpbmUud2ViLnRlc3QiIF0gfQp1WGNlNHNPa2VWZ0tiY01hN2JvTERyTHYwVnF1VXdJQktGY0kzRjZSNlFCNHJuZXUxaGdFWVhGWWNNek04NWlqClp5RmZTamR2bGNyV2dPMEt2cSs2T05PeTdCMkM5c2xJQmNBcURnWmp0dkRyUGFMamNWZEpocGxVMUVlMm9ubFcKdmE0NnFpNDZLdm1hZk1hTDBHRGVTZkc4RXp2MHJ4VXZZMnd6czRSNmtpVThTK3hRKzJkSGFZQWNzK2tRWXlBVQpjcUFFYXFJWVI4bFJibXVVN0orUGRZcHhLQWdrQUJ0cFBPK0tPdEczZUp4eVB5MG43dWlnejgvWWwzYklQdHh5CjA1TGM0OWZ4Sys0QVJWREptcXBCVEQ3VWtxeHExckpsOGJqUzBNRVlKREFiTEowd3Y4Q0pVdUd5RmErQ0JTaFQKa2dxVzRUd0pXZk1wM3F5QW5MMGhMQT09Cg==",
  unknownPerson:
    "https://easyvatstore.blob.core.windows.net/maincontainer/unknown-person.png",
  // tslint:disable-next-line:max-line-length
  scanLicense:
    "eyAiZGVidWdSZXBvcnRpbmciOiAib24iLCAiaW1hZ2VSZXBvcnRDYWNoaW5nIjogZmFsc2UsICJqc0lkZW50aWZpZXIiOiBbICJlYXN5LXZhdC1hcHAuYXp1cmV3ZWJzaXRlcy5uZXQiIF0sICJsaWNlbnNlS2V5VmVyc2lvbiI6IDIsICJtYWpvclZlcnNpb24iOiAiMjAiLCAibWF4RGF5c05vdFJlcG9ydGVkIjogMCwgInBpbmdSZXBvcnRpbmciOiB0cnVlLCAicGxhdGZvcm0iOiBbICJKUyIgXSwgInNjb3BlIjogWyAiQUxMIiBdLCAic2hvd1BvcFVwQWZ0ZXJFeHBpcnkiOiBmYWxzZSwgInNob3dXYXRlcm1hcmsiOiBmYWxzZSwgInRvbGVyYW5jZURheXMiOiAwLCAidmFsaWQiOiAiMjAyMC0wOS0wOSIgfQpmdzZHQVFIM3I2Zi81SWdZU0hZSjdxcWZrNGQwcmFmSUY3L1ZNc0xlaldiK3R2L3dkVEM1elVjNjFMLzVLWmdkClRQTk5jaUduNXBCL01wTHd4ZWMzdndoZzhrUGVMeUhNMVhMYm1QekxLSUV5bk5JUkdHTG5WM3ZJdDUrM3FSa2wKSW9NeXQxQjI0YmVXWnlaWjRJc1dFSVZkem10S1hpZFN3YzQxYzI1dm85SGpEdUhqUkNld3llRC9CMmUwTEVaSQppME10cElTOGZxRUdTRVNzaURabDJvakVKcHdBdHBJeHQwMWNUVjRULzlZT3pGMmRGcnp3bHFNdEduNW1ob255CjRRb0R4Wll3Wkd3RHB0S2VzRGVIaXpkM0VqWFBOTi9ycEZMSUhabE1wS0dPcGR4T3FubWlmZmlNMVU1ZExBNjcKcjZ0VlVNV09kckZTYS8vNmZyejFOUT09Cg==",
    tempToken :
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDbGFpbUlkIjoiYTI1YWY0Y2MtYzI4Ni00NTc4LTE1MmEtMDhkNzgzM2EzM2Q1IiwiZXhwIjoxNjI4MDk2NzU2LCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUxNjMyIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MTYzMiJ9.CJBUsZ7gGuLc6xSes5I8rv3w68ugsqAMcgrCXn9ko6A"
  };
